runtime: python27
api_version: '1'
env: standard
threadsafe: true
handlers:
  - url: /
    secure: always
    application_readable: false
    static_files: index.html
    upload: index.html
  - url: /(.*)
    secure: always
    application_readable: false
    static_files: \1
    upload: (.*)
